#!/usr/bin/env python3
"""Generate publication figures and tables supported by committed data.

No headline sensor-fusion values are synthesized. Figures that require future
electrical/evasion results are defined in docs/FIGURE_DATA_CONTRACT.md.
"""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
FIGURES = ROOT / "results" / "figures"
TABLES = ROOT / "results" / "tables"

COLORS = {
    "training": "#C73E1D",
    "inference": "#2E6F9E",
    "non_ml": "#4B8B3B",
    "neutral": "#4D4D4D",
    "accent": "#7B4EA3",
}


def configure() -> None:
    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 9,
        "axes.titlesize": 10,
        "axes.labelsize": 9,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "legend.fontsize": 8,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "axes.spines.top": False,
        "axes.spines.right": False,
    })


def save(fig: plt.Figure, name: str) -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    for suffix in ("pdf", "svg", "png"):
        fig.savefig(FIGURES / f"{name}.{suffix}", bbox_inches="tight", pad_inches=0.04,
                    dpi=200 if suffix == "png" else None)
    plt.close(fig)


def host_gpu(run_id: str, gpu_index: int) -> str:
    match = re.search(r"_(node2|verifier|testbed-node1)-gpu", run_id)
    host = match.group(1) if match else "unknown"
    return f"{host}\nGPU {gpu_index}"


def trace_duration_hours(path: str, gpu_index: int) -> float:
    frame = pd.read_csv(ROOT / path, usecols=["status", "gpu_index", "t_target_raw_s"])
    frame = frame[(frame["status"] == "ok") & (frame["gpu_index"] == gpu_index)]
    if len(frame) < 2:
        return 0.0
    return float(frame["t_target_raw_s"].iloc[-1] - frame["t_target_raw_s"].iloc[0]) / 3600.0


def corpus_outputs(labels: pd.DataFrame) -> None:
    labels = labels.copy()
    labels["host_gpu"] = [host_gpu(r.run_id, int(r.gpu_index)) for r in labels.itertuples()]
    class_order = {"training": 0, "inference": 1, "non_ml": 2}
    family_class = labels.groupby("family")["label"].first().to_dict()
    families = sorted(labels["family"].unique(), key=lambda f: (class_order[family_class[f]], f))
    gpu_order = sorted(labels["host_gpu"].unique(), key=lambda x: ("verifier" not in x, x))
    pivot = labels.pivot_table(index="family", columns="host_gpu", values="run_id", aggfunc="count", fill_value=0)
    pivot = pivot.reindex(index=families, columns=gpu_order, fill_value=0)

    fig, ax = plt.subplots(figsize=(7.0, 4.8))
    image = ax.imshow(pivot.to_numpy(), cmap="Blues", vmin=0, vmax=max(1, int(pivot.to_numpy().max())), aspect="auto")
    ax.set_xticks(range(len(gpu_order)), gpu_order)
    ax.set_yticks(range(len(families)), [f.replace("_", " ") for f in families])
    ax.set_xlabel("Physical GPU")
    ax.set_ylabel("Workload family")
    ax.set_title("Committed NVML corpus coverage (run counts)")
    for row in range(len(families)):
        for column in range(len(gpu_order)):
            value = int(pivot.iloc[row, column])
            if value:
                ax.text(column, row, str(value), ha="center", va="center", fontsize=7,
                        color="white" if value > pivot.to_numpy().max() / 2 else "black")
    colorbar = fig.colorbar(image, ax=ax, pad=0.015, fraction=0.035)
    colorbar.set_label("Runs")
    save(fig, "corpus-coverage")

    labels["gpu_hours"] = [
        trace_duration_hours(row.trace_path, int(row.gpu_index))
        for row in labels.itertuples()
    ]
    exposure = (labels.groupby(["label", "family"], sort=False)
                .agg(runs=("run_id", "nunique"),
                     gpus=("gpu_uuid", "nunique"),
                     days=("collection_day", "nunique"),
                     gpu_hours=("gpu_hours", "sum"))
                .reset_index())
    exposure["gpu_hours"] = exposure["gpu_hours"].round(3)
    TABLES.mkdir(parents=True, exist_ok=True)
    exposure.to_csv(TABLES / "corpus-exposure.csv", index=False)
    (TABLES / "corpus-exposure.tex").write_text(
        exposure.to_latex(index=False, escape=True, float_format="%.3f")
    )

    totals = labels.groupby("label").agg(runs=("run_id", "nunique"), gpu_hours=("gpu_hours", "sum"))
    negative_hours = float(totals.loc[["inference", "non_ml"], "gpu_hours"].sum())
    macros = (
        "% Generated by scripts/figures/make_existing_figures.py\n"
        f"\\newcommand{{\\CurrentCorpusRuns}}{{{len(labels)}}}\n"
        f"\\newcommand{{\\CurrentTrainingRuns}}{{{int(totals.loc['training', 'runs'])}}}\n"
        f"\\newcommand{{\\CurrentNegativeRuns}}{{{int(totals.loc['inference', 'runs'] + totals.loc['non_ml', 'runs'])}}}\n"
        f"\\newcommand{{\\CurrentNegativeHours}}{{{negative_hours:.2f}}}\n"
    )
    generated = ROOT / "paper" / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    (generated / "current_evidence.tex").write_text(macros)


def baseline_figure() -> None:
    result = json.loads((ROOT / "results" / "e2_baseline_combined.json").read_text())
    folds = pd.DataFrame(result["folds"])
    aggregate_tp = int(folds["tp"].sum())
    aggregate_fn = int(folds["fn"].sum())
    aggregate_fp = int(folds["fp"].sum())
    aggregate_tn = int(folds["tn"].sum())

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.35))
    x = np.arange(len(folds))
    axes[0].plot(x, folds["window_auc_training"], marker="o", color=COLORS["inference"], linewidth=1.5)
    axes[0].set_ylim(0.90, 1.005)
    axes[0].set_xticks(x, [f"F{i}" for i in x])
    axes[0].set_ylabel("Window ROC-AUC")
    axes[0].set_xlabel("Run-grouped fold")
    axes[0].set_title("Diagnostic window discrimination")
    axes[0].grid(axis="y", alpha=0.25)

    axes[1].plot(x, folds["run_tpr"], marker="o", color=COLORS["training"], linewidth=1.5, label="Training TPR")
    axes[1].plot(x, folds["run_fpr"], marker="s", color=COLORS["non_ml"], linewidth=1.5, label="Non-training FPR")
    axes[1].set_ylim(-0.03, 1.05)
    axes[1].set_xticks(x, [f"F{i}" for i in x])
    axes[1].set_ylabel("Run-level rate")
    axes[1].set_xlabel("Run-grouped fold")
    axes[1].set_title(f"Aggregate: {aggregate_tp}/{aggregate_tp + aggregate_fn} TP, {aggregate_fp}/{aggregate_fp + aggregate_tn} FP")
    axes[1].grid(axis="y", alpha=0.25)
    axes[1].legend(frameon=False, loc="center right")
    fig.suptitle("Reconstructed NVML baseline — pipeline diagnostic, not a transfer result", y=1.04, fontsize=10)
    fig.tight_layout()
    save(fig, "baseline-diagnostic")

    audit = pd.DataFrame([{
        "evaluation": "Run-grouped diagnostic",
        "training_runs_detected": f"{aggregate_tp}/{aggregate_tp + aggregate_fn}",
        "nontraining_false_positive_runs": f"{aggregate_fp}/{aggregate_fp + aggregate_tn}",
        "negative_gpu_hours": 11.453,
        "zero_event_upper_95_per_gpu_hour": 0.262,
        "publication_transfer_result": False,
    }])
    audit.to_csv(TABLES / "baseline-audit.csv", index=False)
    (TABLES / "baseline-audit.tex").write_text(audit.to_latex(index=False, escape=True))


def generalization_outputs() -> None:
    """Compare leakage control with actual held-out-domain protocols."""
    specifications = [
        ("Run grouped", "run", "baseline-run-grouped.json"),
        ("Held-out GPU", "GPU", "baseline-gpu-grouped.json"),
        ("Held-out family", "family", "baseline-family-grouped.json"),
        ("Held-out day", "day", "baseline-day-grouped.json"),
    ]
    rows = []
    for label, group, filename in specifications:
        path = ROOT / "results" / "evaluation" / filename
        if not path.exists():
            continue
        result = json.loads(path.read_text())
        aggregate = result["aggregate"]
        folds = result["folds"]
        evaluated = sum(fold.get("status") == "evaluated" for fold in folds)
        skipped = sum(fold.get("status") != "evaluated" for fold in folds)
        rows.append({
            "protocol": label,
            "held_out_unit": group,
            "evaluated_folds": evaluated,
            "non_estimable_folds": skipped,
            "tp": aggregate["tp"],
            "fn": aggregate["fn"],
            "fp": aggregate["fp"],
            "tn": aggregate["tn"],
            "training_tpr": aggregate["run_tpr"],
            "tpr_ci_95_low": aggregate["run_tpr_ci_95"][0] if aggregate["run_tpr_ci_95"] else None,
            "tpr_ci_95_high": aggregate["run_tpr_ci_95"][1] if aggregate["run_tpr_ci_95"] else None,
            "negative_gpu_hours": aggregate["negative_gpu_hours"],
            "false_alerts_per_gpu_hour": aggregate["false_alerts_per_gpu_hour"],
            "zero_event_upper_95": aggregate["zero_event_rate_upper_95"],
        })
    if not rows:
        return

    audit = pd.DataFrame(rows)
    audit.to_csv(TABLES / "generalization-audit.csv", index=False)
    compact_rows = []
    for row in audit.itertuples():
        training_total = row.tp + row.fn
        negative_total = row.fp + row.tn
        if pd.isna(row.training_tpr):
            tpr_text = "--"
            detected_text = "--"
        else:
            tpr_text = f"{row.training_tpr:.3f} [{row.tpr_ci_95_low:.3f}, {row.tpr_ci_95_high:.3f}]"
            detected_text = f"{row.tp}/{training_total}"
        if pd.isna(row.false_alerts_per_gpu_hour):
            rate_text = "--"
        elif pd.notna(row.zero_event_upper_95):
            rate_text = f"0 (<{row.zero_event_upper_95:.3f})"
        else:
            rate_text = f"{row.false_alerts_per_gpu_hour:.3f}"
        compact_rows.append({
            "protocol": row.protocol,
            "folds evaluated": f"{row.evaluated_folds}/{row.evaluated_folds + row.non_estimable_folds}",
            "training detected": detected_text,
            "false alerts": f"{row.fp}/{negative_total}",
            "TPR [95% CI]": tpr_text,
            "FA/GPU-h": rate_text,
        })
    (TABLES / "generalization-audit.tex").write_text(
        pd.DataFrame(compact_rows).to_latex(index=False, escape=True)
    )

    plotted = audit[audit["training_tpr"].notna()].copy()
    x = np.arange(len(plotted))
    tpr = plotted["training_tpr"].to_numpy(dtype=float)
    lower = plotted["tpr_ci_95_low"].to_numpy(dtype=float)
    upper = plotted["tpr_ci_95_high"].to_numpy(dtype=float)
    false_rate = plotted["false_alerts_per_gpu_hour"].to_numpy(dtype=float)
    upper_bound = plotted["zero_event_upper_95"].to_numpy(dtype=float)

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.65))
    bar_colors = [COLORS["neutral"], COLORS["inference"], COLORS["training"], COLORS["accent"]]
    axes[0].bar(x, tpr, color=bar_colors[:len(plotted)])
    axes[0].errorbar(x, tpr, yerr=np.vstack((tpr - lower, upper - tpr)),
                     fmt="none", ecolor="black", capsize=3, linewidth=1)
    axes[0].set_xticks(x, plotted["protocol"], rotation=18, ha="right")
    axes[0].set_ylim(0, 1.08)
    axes[0].set_ylabel("Training run TPR")
    axes[0].set_title("Transfer recall")
    axes[0].grid(axis="y", alpha=0.25)

    axes[1].bar(x, false_rate, color=bar_colors[:len(plotted)])
    for index, bound in enumerate(upper_bound):
        if np.isfinite(bound):
            axes[1].plot([index], [bound], marker="v", color="black", markersize=5)
    axes[1].axhline(0.1, color=COLORS["accent"], linestyle="--", linewidth=1,
                    label="0.1/GPU-h target")
    axes[1].set_xticks(x, plotted["protocol"], rotation=18, ha="right")
    axes[1].set_ylim(0, max(1.0, float(np.nanmax(false_rate)) * 1.15))
    axes[1].set_ylabel("False alerts / negative GPU-hour")
    axes[1].set_title("False-alert exposure")
    axes[1].grid(axis="y", alpha=0.25)
    axes[1].legend(frameon=False, loc="upper left")
    fig.suptitle("Evaluation protocol changes the baseline conclusion", y=1.02, fontsize=10)
    fig.tight_layout()
    save(fig, "generalization-audit")


def wave_figure() -> None:
    hardware = pd.read_csv(ROOT / "results" / "wave" / "overhead_3090_hw.csv")
    full = pd.read_csv(ROOT / "results" / "wave" / "overhead_3090_all.csv")
    labels = []
    for model_id in hardware["model_id"]:
        family = model_id.split("_", 1)[0].upper()
        hidden = re.search(r"embd(\d+)", model_id).group(1)
        labels.append(f"{family}\nd={hidden}")
    x = np.arange(len(labels))
    fig, ax = plt.subplots(figsize=(7.0, 2.8))
    ax.plot(x, hardware["overhead_percent"], marker="o", linewidth=1.5,
            color=COLORS["inference"])
    ax.plot(x, full["overhead_percent"], marker="s", linewidth=1.5,
            color=COLORS["training"])
    ax.set_yscale("log")
    ax.set_xticks(x, labels)
    ax.set_ylabel("Runtime overhead (%) — log scale")
    ax.set_xlabel("Decoder configuration")
    ax.set_title("WAVE profiling overhead on a 200 W-capped RTX 3090")
    ax.set_xlim(-0.25, len(labels) + 0.7)
    ax.text(len(labels) - 0.75, float(full["overhead_percent"].iloc[-1]) * 1.08,
            f"WAVE metrics · mean {full.overhead_percent.mean():.0f}%",
            color=COLORS["training"], ha="right", va="bottom", fontsize=8)
    ax.text(len(labels) - 0.75, float(hardware["overhead_percent"].iloc[-1]) * 0.94,
            f"One NCU metric · mean {hardware.overhead_percent.mean():.0f}%",
            color=COLORS["inference"], ha="right", va="top", fontsize=8)
    ax.grid(axis="y", which="both", alpha=0.25)
    save(fig, "wave-overhead")

    summary = pd.DataFrame([
        {"metric_set": "One NCU metric", "configurations": len(hardware),
         "minimum_overhead_pct": hardware.overhead_percent.min(),
         "maximum_overhead_pct": hardware.overhead_percent.max(),
         "mean_overhead_pct": hardware.overhead_percent.mean()},
        {"metric_set": "WAVE metric set", "configurations": len(full),
         "minimum_overhead_pct": full.overhead_percent.min(),
         "maximum_overhead_pct": full.overhead_percent.max(),
         "mean_overhead_pct": full.overhead_percent.mean()},
    ])
    summary.to_csv(TABLES / "wave-overhead-summary.csv", index=False)
    (TABLES / "wave-overhead-summary.tex").write_text(
        summary.to_latex(index=False, escape=True, float_format="%.1f")
    )


def testbed_table() -> None:
    inventories = [
        ("node2", ROOT / "results" / "inventory-node2" / "gpus.csv", "NVML fleet"),
        ("verifier", ROOT / "results" / "inventory-verifier" / "gpus.csv", "NVML + electrical"),
        ("testbed-node1", ROOT / "results" / "inventory-testbed-node1" / "gpus.csv", "WAVE reproduction"),
    ]
    rows = []
    for host, path, role in inventories:
        frame = pd.read_csv(path, skipinitialspace=True)
        frame.columns = [column.strip() for column in frame.columns]
        for _, row in frame.iterrows():
            rows.append({
                "host": host,
                "gpu_index": int(row["index"]),
                "gpu_uuid": row["uuid"],
                "pci_bus": row["pci.bus_id"],
                "pcie_width": int(row["pcie.link.width.current"]),
                "vbios": row["vbios_version"],
                "power_limit_w": float(str(row["power.limit [W]"]).replace(" W", "")),
                "paper_role": role,
            })
    table = pd.DataFrame(rows)
    table.to_csv(TABLES / "testbed-gpus.csv", index=False)
    printable = table.copy()
    printable["gpu_uuid"] = printable["gpu_uuid"].str.slice(0, 17) + "..."
    (TABLES / "testbed-gpus.tex").write_text(
        printable.to_latex(index=False, escape=True, float_format="%.0f")
    )


def calibration_figure() -> None:
    rows = []
    path = ROOT / "results" / "e1_calibration_node2.md"
    for line in path.read_text().splitlines():
        if not line.startswith("|") or "run_id" in line or "---" in line:
            continue
        fields = [field.strip() for field in line.strip("|").split("|")]
        if len(fields) != 9 or not fields[3].startswith("nvml.") or fields[7] in {"None", ""}:
            continue
        match = re.search(r"_(node2|verifier)-gpu(\d+)", fields[0])
        if not match:
            continue
        rows.append({
            "gpu": f"{match.group(1)}-{match.group(2)}",
            "health": fields[4],
            "alignment_ms": float(fields[7]),
        })
    frame = pd.DataFrame(rows)
    order = sorted(frame["gpu"].unique())
    fig, ax = plt.subplots(figsize=(7.0, 2.8))
    rng = np.random.default_rng(0)
    for health, marker in [("pass", "o"), ("fail", "x")]:
        subset = frame[frame["health"] == health]
        positions = np.array([order.index(value) for value in subset["gpu"]], dtype=float)
        positions += rng.uniform(-0.12, 0.12, len(positions))
        ax.scatter(positions, subset["alignment_ms"], marker=marker, s=24,
                   color=COLORS["non_ml"] if health == "pass" else COLORS["training"],
                   label=health.capitalize(), alpha=0.85)
    ax.axhline(100, color=COLORS["neutral"], linestyle="--", linewidth=1, label="Frozen 100 ms limit")
    ax.set_xticks(range(len(order)), order, rotation=30, ha="right")
    ax.set_ylabel("Alignment error (ms)")
    ax.set_xlabel("Host and physical GPU")
    ax.set_title("Calibration gates expose and preserve superseded logger attempts")
    ax.grid(axis="y", alpha=0.25)
    ax.legend(frameon=False, ncol=3)
    save(fig, "calibration-alignment")


def main() -> int:
    configure()
    labels = pd.read_csv(ROOT / "results" / "e2_labels_combined.csv")
    if labels["gpu_uuid"].isna().any():
        raise SystemExit("Run `make data-audit` before generating publication figures")
    corpus_outputs(labels)
    baseline_figure()
    generalization_outputs()
    wave_figure()
    calibration_figure()
    testbed_table()
    print(f"Generated figures under {FIGURES}")
    print(f"Generated tables under {TABLES}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
